### ISSUE TITLE
Block Client IPs via subnet or introduce a new configuration key?

### ISSUE THREAD

**Issue by Falcosc** [nikp123/wake-on-arp#14]
I have an unusual request, I want to block a Client IP from the Wake on ARP feature.

My Kodi client doesn't behave very well. Kodi regularly scans for new files and this does wake my server up. But Kodi has a WOL feature to wake up the file server only on actual file requests. Because my Kodi client doesn't use other apps like file explorer, it doesn't need the Wake on ARP feature, and it would be great to blacklist ARP requests from my Kodi Client IP.

Would be nice if the excluded IPs would be listed here as well: https://github.com/nikp123/wake-on-arp/blob/master/src/main.c#L134

On the other hand, I could just use a 25er mask and move the kodi client to IP 128

**Comment by Falcosc** [comment]
The subnet hack did work well.

My Kodi Client can not wake up others via ARP, but all other clients can still wake up Kodi client via ARP.

**Comment by nikp123** [comment]
This should work.

**Comment by Falcosc** [comment]
Cool, now we have 2 ways to deal with it. The subnet 25 test was still worth it because it did discover the endian bug.
